### PR TITLE
Double 'well' in TOC is fixed

### PR DESCRIPTION
**Pull request by solomax**
Thanks a lot for your work on this project :))

### CODE REVIEW

**Comment by devacfr** [comment]
thx, do you want I release this minor change ?

**Comment by solomax** [comment]
I was unable to find maven repo for this plugin :(((
So I have added it to bintray of our project.

I can wait until #9 will be fixed ;))
I can try to help with this, but I found no way to debug *.vm template :(( so not sure how you are able to develop this plugin :)

**Comment by devacfr** [comment]
could you send me a sample, to reduce the time ? I will try fix for the end of this week.

**Comment by solomax** [comment]
Sure, here is the result: https://builds.apache.org/view/M-R/view/OpenMeetings/job/openmeetings/site/openmeetings-server/index.html
I'll create small 'quickstart' project and will send you the link

Which maven repository are you using for releases?

**Comment by devacfr** [comment]
```
<repository>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
  <id>bintray-devacfr-maven</id>
  <name>bintray</name>
  <url>https://dl.bintray.com/devacfr/maven</url>
 </repository>
```
For the moment, I plan to put in maven central.

**Comment by devacfr** [comment]
Ok thx for sample. I'm working on it.

**Comment by solomax** [comment]
Is it enough? Or maybe you need "complete" small maven project?

**Comment by devacfr** [comment]
no, I understand. You want remove all sections of carousel in the TOC.

**Comment by solomax** [comment]
yes, exactly, IMO it is useless in the TOC
Thanks :)))

**Pull request merged**
