### PR TITLE
If "publishDate position" is set to "none" don't generate the date into the comments

### PR DESCRIPTION
**Pull request by chrisdutz**
We are using this skin to automatically generate the Apache PLC4X website (https://plc4x.apache.org) by our CI server.

We have one little issue with this skin in its current state: It always modifies every generated file at least once a day. This is due to the fact that the day is always generated into the comment at the top.

with the default Maven skins, usually you prevent it generating such dates by setting:
`<publishDate position="none"/>`.

This pull request simply prevents the date from being output, if this is set.

### CODE REVIEW

**Comment by chrisdutz** [comment]
This is the default way to configure this: 
http://maven.apache.org/plugins-archives/maven-site-plugin-3.0/examples/sitedescriptor.html

**Comment by devacfr** [comment]
Thank you.
Do you want I release this change ?

**Comment by devacfr** [comment]
I do not think so :P

**Comment by devacfr** [comment]
I published release 1.4.0 on https://oss.sonatype.org/content/repositories/releases/. You need wait for replication on maven central http://central.maven.org/maven2/.

**Pull request merged**
